version: '3.3'
services:
  msrmq_socketio_ts_server:
    image: socketio-ts-node-server-image
    container_name: ms-socketio-ts-server-container
    build:
      # let docker know that we build with dockerfile in locally instead of dockerhub
      context: . # which is the directory dockerfile will be searched for
      dockerfile: Dockerfile # the file name that will be build
    ports:
      - "86:5000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - ms_rmq_network
      - local_central_db_network
networks:
  ms_rmq_network:
    external: true
  local_central_db_network:
    external: true
