version: '3.3'
services:
  export:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    container_name: ms-rmq-export-container
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 801:8000
    depends_on:
      - export_db
    networks:
      - ms-rmq-network

  export_db:
    image: mysql:5.7.22
    container_name: ms-rmq-export-db-container
    environment:
      MYSQL_DATABASE: export
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306

networks:
  ms-rmq-network:
    driver: bridge

