version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "221:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
