version: '3.3'
services:
  import:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    container_name: ms-rmq-import-container
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 802:8000
    depends_on:
      - import_db
    networks:
      - ms_rmq_network
  import_db:
    image: mysql:5.7.22
    container_name: ms-rmq-import-db-container
    environment:
      MYSQL_DATABASE: import
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
    networks:
      - ms_rmq_network
networks:
  ms_rmq_network:
    external: true

