version: '3.3'
services:
  msrmq-rabbitmq:
    build: .
    container_name: ms-rmq-container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - local_central_rabbitmq_network
networks:
  local_central_rabbitmq_network:
    external: true