version: '3.3'
services:
  msrmq_export:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    container_name: ms-rmq-export-container
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 801:8000
    networks:
      - ms_rmq_network
networks:
  ms_rmq_network:
    external: true

