version: '3.3'
services:
    msrmq_socketio_server:
      image: socketio-node-server-image
      container_name: ms-socketio-server-container
      build:          # let docker know that we build with dockerfile in locally instead of dockerhub
        context: .   # which is the directory dockerfile will be searched for
        dockerfile: Dockerfile    # the file name that will be build
      ports:
        - "803:5000"
      volumes:
        - .:/app
      stdin_open: true
      tty: true
      networks:
      - ms_rmq_network
    msrmq_socketio_mongo_db:
      image: mongo
      container_name: ms-socketio-mongo-db-container
      ports:
        - "27017:27017"
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
        - ./mongo_db:/data/db
      networks:
        - ms_rmq_network
networks:
  ms_rmq_network:
    external: true